load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "ThreadTrackerTest",
    srcs = ["ThreadTrackerTest.java"],
    test_class = "clerk.profilers.thread.ThreadTrackerTest",
    deps = [
        "//src/clerk/profilers/thread",
    ],
)
