load("@rules_java//java:defs.bzl", "java_library")

java_library(
  name = "clerk",
  visibility = ["//visibility:public"],
  srcs = [
    "Clerk.java",
    "ClerkExecutor.java",
    "Processor.java",
  ],
  deps = [
    "//clerk/util:logger",
  ],
)
