load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "SingleStorageTest",
  srcs = ["SingleStorageTest.java"],
  test_class = "clerk.storage.SingleStorageTest",
  deps = [
    "//java/clerk/storage",
  ],
)

java_test(
  name = "PairStorageTest",
  srcs = ["PairStorageTest.java"],
  test_class = "clerk.storage.PairStorageTest",
  deps = [
    "//java/clerk/storage",
  ],
)

java_test(
  name = "ListStorageTest",
  srcs = ["ListStorageTest.java"],
  test_class = "clerk.storage.ListStorageTest",
  deps = [
    "//java/clerk/storage",
  ],
)

java_test(
  name = "ClassMappedStorageTest",
  srcs = ["ClassMappedStorageTest.java"],
  test_class = "clerk.storage.ClassMappedStorageTest",
  deps = [
    "//java/clerk/storage",
  ],
)

java_test(
  name = "ClassMappedListStorageTest",
  srcs = ["ClassMappedListStorageTest.java"],
  test_class = "clerk.storage.ClassMappedListStorageTest",
  deps = [
    "//java/clerk/storage",
  ],
)
