load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "ReturnableListStorageTest",
  srcs = ["ReturnableListStorageTest.java"],
  test_class = "clerk.data.ReturnableListStorageTest",
  deps = [
    "//java/clerk/data",
  ],
)

java_test(
  name = "PairStorageTest",
  srcs = ["PairStorageTest.java"],
  test_class = "clerk.data.PairStorageTest",
  deps = [
    "//java/clerk/data",
  ],
)
