load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "FixedPeriodPolicyTest",
  srcs = ["FixedPeriodPolicyTest.java"],
  test_class = "clerk.data.FixedPeriodPolicyTest",
  deps = [
    "//java/clerk/data:policies",
  ],
)

java_test(
  name = "SingleCollectionPolicyTest",
  srcs = ["SingleCollectionPolicyTest.java"],
  test_class = "clerk.data.SingleCollectionPolicyTest",
  deps = [
    "//java/clerk/data:policies",
  ],
)

java_test(
  name = "PairStorageTest",
  srcs = ["PairStorageTest.java"],
  test_class = "clerk.data.PairStorageTest",
  deps = [
    "//java/clerk/data:processors",
  ],
)

java_test(
  name = "ReturnableListStorageTest",
  srcs = ["ReturnableListStorageTest.java"],
  test_class = "clerk.data.ReturnableListStorageTest",
  deps = [
    "//java/clerk/data:processors",
  ],
)
