load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "PeriodicExecutorTest",
  srcs = ["PeriodicExecutorTest.java"],
  test_class = "clerk.concurrent.PeriodicExecutorTest",
  deps = [
    "//java/clerk/concurrent",
  ],
)

java_test(
  name = "SettablePeriodicExecutorTest",
  srcs = ["SettablePeriodicExecutorTest.java"],
  test_class = "clerk.concurrent.SettablePeriodicExecutorTest",
  deps = [
    "//java/clerk/concurrent",
  ],
)
