load("@rules_java//java:defs.bzl", "java_library")

java_library(
  name = "data",
  visibility = ["//visibility:public"],
  srcs = [
    "DummyStorage.java",
  ],
  deps = [
    "//java/clerk",
  ],
)
