load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "TimerTest",
    srcs = ["TimerTest.java"],
    test_class = "clerk.profilers.timer.TimerTest",
    deps = [
        "//src/clerk/profilers/timer",
    ],
)
