load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "DirectCollectorTest",
  srcs = ["DirectCollectorTest.java"],
  test_class = "clerk.util.DirectCollectorTest",
  deps = [
    "//java/clerk/util",
    "//java/clerk/testing",
  ],
)

java_test(
  name = "ListStorageTest",
  srcs = ["ListStorageTest.java"],
  test_class = "clerk.util.ListStorageTest",
  deps = [
    "//java/clerk/util",
    "//java/clerk/testing",
  ],
)

java_test(
  name = "PairStorageTest",
  srcs = ["PairStorageTest.java"],
  test_class = "clerk.util.PairStorageTest",
  deps = [
    "//java/clerk/util",
    "//java/clerk/testing",
  ],
)
