load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "ClerkUtilTest",
  srcs = ["ClerkUtilTest.java"],
  test_class = "clerk.util.ClerkUtilTest",
  deps = [
    "//clerk/data",
    "//clerk/util",
  ],
)
