load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "DirectCollectorTest",
  srcs = ["DirectCollectorTest.java"],
  test_class = "clerk.collectors.DirectCollectorTest",
  deps = [
    "//java/clerk/collectors",
    "//java/clerk/storage",
  ],
)
