load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "DirectCollectorTest",
  srcs = ["DirectCollectorTest.java"],
  test_class = "clerk.util.DirectCollectorTest",
  deps = [
    "//java/clerk/util",
  ],
)

java_test(
  name = "FixedPeriodCollectorTest",
  srcs = ["FixedPeriodCollectorTest.java"],
  test_class = "clerk.util.FixedPeriodCollectorTest",
  deps = [
    "//java/clerk/util",
  ],
)
