load("@rules_java//java:defs.bzl", "java_library")

java_library(
  name = "profilers",
  visibility = ["//visibility:public"],
  srcs = [
    "DataSorter.java",
  ],
  deps = [
    "//core/clerk",
  ]
)
