load("@rules_java//java:defs.bzl", "java_binary")

java_library(
  name = "data",
  visibility = ["//visibility:public"],
  srcs = [
    "ListStorage.java",
    "RelativePairStorage.java",
  ],
  deps = [
    "//clerk",
  ]
)
