load("@rules_java//java:defs.bzl", "java_library")

java_library(
  name = "utils",
  visibility = [
    "//src/clerk:__subpackages__",
    "//test/clerk:__subpackages__"
  ],
  srcs = glob(["*.java"]),
)
