load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "MathUtilsTest",
    srcs = ["MathUtilsTest.java"],
    test_class = "clerk.utils.MathUtilsTest",
    deps = [
        "//src/clerk/utils",
    ],
)
