load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "FakeStorageTest",
  srcs = ["FakeStorageTest.java"],
  test_class = "clerk.testing.FakeStorageTest",
  deps = [
    "//java/clerk/testing",
  ],
)

java_test(
  name = "PairTest",
  srcs = ["PairTest.java"],
  test_class = "clerk.testing.PairTest",
  deps = [
    "//java/clerk/testing",
  ],
)
