load("@rules_java//java:defs.bzl", "java_library")

java_library(
  name = "data",
  visibility = ["//visibility:public"],
  srcs = [
    "SynchronousExecutor.java",
    "AsynchronousSteadyStateExecutor.java",
  ],
  deps = ["//clerk"],
)
