load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "DummyStorageTest",
  srcs = ["DummyStorageTest.java"],
  test_class = "clerk.examples.data.DummyStorageTest",
  deps = [
    "//clerk/data",
  ],
)

java_test(
  name = "ListStorageTest",
  srcs = ["ListStorageTest.java"],
  test_class = "clerk.data.ListStorageTest",
  deps = [
    "//clerk/data",
  ],
)

java_test(
  name = "PairStorageTest",
  srcs = ["PairStorageTest.java"],
  test_class = "clerk.data.PairStorageTest",
  deps = [
    "//clerk/data",
  ],
)
