load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "SteadyStateSchedulerTest",
  srcs = ["SteadyStateSchedulerTest.java"],
  test_class = "clerk.scheduling.SteadyStateSchedulerTest",
  deps = [
    "//clerk/scheduling",
  ],
)
