load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "DummyStorageTest",
  srcs = ["DummyStorageTest.java"],
  test_class = "clerk.testing.data.DummyStorageTest",
  deps = [
    "//java/clerk/testing/data",
  ],
)
