workspace(name = "clerk_examples")

local_repository(
  name = "clerk",
  path = "../..",
)

load("@clerk//:clerk_deps.bzl", "clerk_deps")
clerk_deps()

local_repository(
  name = "vanilla_clerk",
  path = "../vanilla",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@dagger//:workspace_defs.bzl", "DAGGER_ARTIFACTS", "DAGGER_REPOSITORIES")

maven_install(
    artifacts = DAGGER_ARTIFACTS,
    repositories = DAGGER_REPOSITORIES,
)
