load("@rules_java//java:defs.bzl", "java_test")

java_test(
    name = "SteadyStateScheduledRunnableTest",
    srcs = ["SteadyStateScheduledRunnableTest.java"],
    test_class = "clerk.concurrent.SteadyStateScheduledRunnableTest",
    deps = [
        "//src/clerk/concurrent",
    ],
)
