load("@rules_java//java:defs.bzl", "java_test")

java_test(
  name = "PeriodicSteadyStateExecutorTest",
  srcs = ["PeriodicSteadyStateExecutorTest.java"],
  test_class = "clerk.concurrent.PeriodicSteadyStateExecutorTest",
  deps = [
    "//clerk/concurrent:steady_state",
  ],
)
