workspace(name = "clerk_jmh_examples")

local_repository(name = "clerk", path = "../..")

load("@clerk//:clerk_deps.bzl", "clerk_deps")
clerk_deps()

load("@rules_jmh//:deps.bzl", "rules_jmh_deps")
rules_jmh_deps()

load("@rules_jmh//:defs.bzl", "rules_jmh_maven_deps")
rules_jmh_maven_deps()
